# Generated by Django 5.0.7 on 2024-12-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='student',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
