# Generated by Django 5.0.7 on 2024-12-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='check_out_time_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date')),
                ('reason', models.TextField(blank=True, help_text='Reason for the leave', null=True)),
                ('approved', models.BooleanField(default=False, help_text='Whether the leave has been approved')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='app1.student')),
            ],
        ),
    ]
